#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_webgpu = env.Clone()

driver_obj = []
env_webgpu.add_source_files(driver_obj, "*.cpp")
env.drivers_sources += driver_obj
